name: teaching
version: '0.1.1'
synopsis: Code examples derived when studying Haskell
author: Andrew Cowie <andrew@operationaldynamics.com>
maintainer: Andrew Cowie <andrew@operationaldynamics.com>
copyright: © 2017-2020 Operational Dynamics, and Others
license: MIT
tested-with: GHC==8.6

ghc-options: -Wall -Wwarn -fwarn-tabs

dependencies:
  - base
  - core-data
  - core-text
  - core-program >= 0.2.4
  - directory

executables:
  descender:
    source-dirs:
      - src
    main: DescenderMain.hs
    ghc-options: -threaded

tests:
  check:
    dependencies:
      - hspec
    ghc-options: -threaded
    source-dirs:
      - tests
    main: TestSuite.hs
    other-modules: []
