name: hello
version: '0.1.1'
synopsis: Hello
author: Andrew Cowie <andrew@operationaldynamics.com>
maintainer: Andrew Cowie <andrew@operationaldynamics.com>
copyright: © 2017-2020 Operational Dynamics, and Others
license: MIT
tested-with: GHC==8.6
ghc-options: -Wall -Wwarn -fwarn-tabs

dependencies:
- base

executables:
  hello:
    main: HelloMain.hs
    source-dirs: src
    ghc-options: -threaded
